In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(arr[2])

3


In [5]:
print(arr[-3])

3


In [6]:
print(arr[0])

1


In [7]:
print(arr[0] + arr[2])

4


In [8]:
ar = np.array([3,4,5,6,7])

In [10]:
print(arr[2] + ar[2])

8


In [11]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print(arr1[1, 2])

7


In [15]:
print(arr1[0, 2])

3


In [16]:
print(arr1[0, 1] + arr1[0, 2])

5


In [23]:
arr2 = np.array([[[1,2,3,4],[2,3,4,5]],[[3,4,5,6],[4,5,6,7]]])

In [24]:
print(arr2)

[[[1 2 3 4]
  [2 3 4 5]]

 [[3 4 5 6]
  [4 5 6 7]]]


In [25]:
print(arr2.ndim)

3


In [26]:
print(arr2[1])

[[3 4 5 6]
 [4 5 6 7]]


In [28]:
print(arr2[-1])

[[3 4 5 6]
 [4 5 6 7]]


In [29]:
print(arr[::-1])

[5 4 3 2 1]


In [30]:
arr3 = np.array([1,2,3,4,5])

In [31]:
print(type(arr3))

<class 'numpy.ndarray'>


In [33]:
print(arr3[1:3])

[2 3]


In [34]:
print(arr3[:0])

[]


In [35]:
print(arr3[1:])

[2 3 4 5]


In [36]:
print(arr3[::-1])

[5 4 3 2 1]


In [38]:
print(arr3[1 :4 :2])

[2 4]


In [39]:
print(arr3[1 :3 :2])

[2]


In [40]:
arr4 = np.array([[1,2,3,4],[5,6,7,8]])

In [41]:
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
print(arr4[1])

[5 6 7 8]


In [44]:
print(arr4[1, 1:3])

[6 7]


In [45]:
print(arr4[0:2, 2])

[3 7]


In [46]:
print(arr4[0:2, 1:3])

[[2 3]
 [6 7]]
