In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
print(arr1.dtype)

int32


In [7]:
a = arr1.copy()

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1[1] = 12

In [12]:
print(arr1)
print(a)

[ 1 12  3  4  5]
[1 2 3 4 5]


In [13]:
b = arr1.view()

In [14]:
print(b)

[ 1 12  3  4  5]


In [15]:
arr1[1] = 22

In [16]:
print(arr1)
print(b)

[ 1 22  3  4  5]
[ 1 22  3  4  5]


In [17]:
print(a.base)

None


In [18]:
print(b.base)

[ 1 22  3  4  5]


In [19]:
print(arr1.base)

None
