In [1]:
import numpy as np

In [2]:
aryy = np.array([1,2,4,5])

In [6]:
print(aryy)
print(type(aryy))
print(aryy.ndim)

[1 2 4 5]
<class 'numpy.ndarray'>
1


In [8]:
print(np.__version__)

1.21.5


In [10]:
ary1 = np.array([[1,2,4,5],[8,7,6,4]])

In [12]:
print(ary1)
print(type(ary1))
print(ary1.ndim)

[[1 2 4 5]
 [8 7 6 4]]
<class 'numpy.ndarray'>
2


In [17]:
ary1 = np.array([[1,2,4,5],[8,7,6,4]], ndmin = 3)

In [19]:
print(ary1)
print(ary1.ndim)

[[[1 2 4 5]
  [8 7 6 4]]]
3


In [28]:
ary2 = np.array([[4,8,8,2],[9,5,2,7]])
print(ary2.size)
print(ary2.shape)
print(ary2.itemsize)
print(ary2.dtype)
print(ary2.reshape(4,2))

8
(2, 4)
4
int32
[[4 8]
 [8 2]
 [9 5]
 [2 7]]


In [32]:
print(type(ary2))

<class 'numpy.ndarray'>
