In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
print(arr1.dtype)

int32


In [7]:
arr2 = np.array(['abc', 'def', 'ghi'])

In [8]:
print(arr2)

['abc' 'def' 'ghi']


In [9]:
print(type(arr2))

<class 'numpy.ndarray'>


In [10]:
print(arr2.dtype)

<U3


In [14]:
arr3 = np.array([1,2,3,4,5], dtype = 'S')

In [15]:
print(arr3)

[b'1' b'2' b'3' b'4' b'5']


In [16]:
print(arr3.dtype)

|S1


In [17]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
arr = np.array([1, 2, 3, 4], dtype='i1')

print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [22]:
# string 'abc' can not be converted to integer

arr = np.array(['abc', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'abc'

In [23]:
print(arr1)

[1 2 3 4 5]


In [26]:
print(arr1.dtype)

int32


In [28]:
new = arr1.astype('S')

In [29]:
print(new)

[b'1' b'2' b'3' b'4' b'5']


In [30]:
print(arr1)

[1 2 3 4 5]


In [31]:
arr4 = np.array([1,0,2,0], dtype = bool)

In [32]:
print(arr4)

[ True False  True False]


In [33]:
arr5 = np.array([1,10,2,20], dtype = bool)

In [34]:
print(arr5)

[ True  True  True  True]


In [37]:
arr4 = np.array([1,'1',0,2,0], dtype = bool)

In [38]:
print(arr4)

[ True  True False  True False]


In [39]:
print(arr4.dtype)

bool
