In [1]:
# join

In [3]:
import numpy as np

In [4]:
ar_1 = np.array([1,2,3,4])
ar_2 = np.array([5,6,7,8,])

In [9]:
ar_3 = np.concatenate((ar_1, ar_2))

In [10]:
print(ar_3)

[1 2 3 4 5 6 7 8]


In [12]:
print(ar_1)
print(ar_2)

[1 2 3 4]
[5 6 7 8]


In [13]:
print(np.concatenate((ar_1, ar_2)))

[1 2 3 4 5 6 7 8]


In [16]:
print(ar_1 + ar_2)

[ 6  8 10 12]


In [14]:
ar_4 = np.array([[1, 2],[3, 4]])
ar_5 = np.array([[5, 6],[7, 8]])

In [15]:
print(ar_4, ar_5)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [18]:
ar_6 = np.concatenate((ar_4, ar_5))
print(ar_6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
ar_7 = np.concatenate((ar_4, ar_5), axis = 1)
print(ar_7)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
ar_8 = np.stack((ar_4, ar_5))
print(ar_8)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
ar_9 = np.hstack((ar_4, ar_5))
print(ar_9)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
ar_10 = np.vstack((ar_4, ar_5))
print(ar_10)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
ar_11 = np.dstack((ar_4, ar_5))
print(ar_11)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [27]:
# split

In [28]:
ar1 = np.array([1,2,3,4,5])

In [29]:
print(ar1)

[1 2 3 4 5]


In [30]:
print(np.array_split(ar1, 2))

[array([1, 2, 3]), array([4, 5])]


In [31]:
print(np.array_split(ar1, 3))

[array([1, 2]), array([3, 4]), array([5])]


In [33]:
ar3 = np.array_split(ar1, 3)

print(ar3[0])
print(ar3[1])
print(ar3[2])

[1 2]
[3 4]
[5]


In [34]:
print(ar3[0] + ar3[1] + ar3[1])

[ 7 10]


In [35]:
ar4 = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(ar4)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]


In [39]:
ar5 = np.array_split(ar4, 3)
print(ar5)

[array([[[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]]]), array([], shape=(0, 1, 4, 2), dtype=int32), array([], shape=(0, 1, 4, 2), dtype=int32)]


In [43]:
ar6 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(ar6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
ar7 = np.array_split(ar6, 3)
print(ar7)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [48]:
print(ar6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
print(np.array_split(ar6, 3, axis = 1))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


In [54]:
print(ar6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
