In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
print(arr1.shape)

(5,)


In [4]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
print(arr2.shape)

(2, 5)


In [6]:
print(arr2.reshape(5,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [8]:
print(arr)

[[[[[1 2 3 4]]]]]


In [9]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
